version: "3.8"

services:

  postgres-restrictions:
    image: postgres:14.0
    container_name: postgres-restrictions
    ports:
      - "${RESTRICTIONS_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ${HOST_DIR}:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    network_mode: host

  grafana:
    image: grafana/grafana:8.2.1
    container_name: grafana
    network_mode: host

  jaeger:
    image: jaegertracing/all-in-one:1.27.0
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250"
