{
 "title": "EHEALTH-Metrics",
 "description": "Metrics about Grafana",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "eHealth-People",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"ehealth-people\"}",
     "legendFormat": "STATUS:"
    }
   ]
  },
  {
   "title": "eHealth-MedTests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"ehealth-medtests\"}",
     "legendFormat": "STATUS:"
    }
   ]
  },
  {
   "title": "eHealth-Certificates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"ehealth-certificates\"}",
     "legendFormat": "STATUS:"
    }
   ]
  },
  {
   "title": "eHealth-Restrictions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"ehealth-restrictions\"}",
     "legendFormat": "{{instance}} STATUS"
    }
   ]
  }
 ]
}