# prometheus.yml
global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ehealth'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8090', 'host.docker.internal:8100', 'host.docker.internal:8110']
