# prometheus.yml
global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ehealth'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['host.docker.internal:${PATIENTS_ENDPOINT_PORT}',
                  'host.docker.internal:${CERTIFICATES_ENDPOINT_PORT}',
                  'host.docker.internal:${MED_TESTS_ENDPOINT_PORT}',
                  'host.docker.internal:${RESTRICTIONS_ENDPOINT_PORT}']
